hw4
ksushavin/nodejs-homework-rest-api pull request #3
Opened 2022-12-26 22:40 UTC by ksushavin

Перевірте, будь-ласка.

2022-12-27 15:58 UTC, BohdanGres requested changes
так все добре, трошки зауважень

2022-12-27 15:58 UTC, BohdanGres commented on app.js
>  app.use('/api/contacts', contactsRouter);
спробуй тут мідлвар навісити, але перевір чи помилки коректно обробляються

2022-12-27 15:58 UTC, BohdanGres commented on middlesweres/authenticate.js
> +        if (!user || !user.token) {
забув user.token === token перевірити

2022-12-27 21:57 UTC, ksushavin commented on controllers/contacts/getAll.js
> +    }
Додала перевірку на favorite, бо інакше getAll давало пустий масив (якщо не вказано favorite).

2022-12-27 21:58 UTC, ksushavin commented on middlesweres/authenticate.js
> +
додала перевірку user.token === token

2022-12-27 22:03 UTC, ksushavin commented on app.js
>  app.use('/api/contacts', contactsRouter);
> спробуй тут мідлвар навісити, але перевір чи помилки коректно обробляються

Спробувала з мідлварою authenticate для запитів контактів - не спрацювало.

2022-12-27 22:04 UTC, ksushavin commented on middlesweres/authenticate.js
> +        if (!user || !user.token) {
> забула user.token === token перевірити

додала перевірку

2022-12-27 22:05 UTC, ksushavin commented on controllers/contacts/getAll.js
> +
додала перевірку на favorite, бо інакше getAll повертав пустий масив

2022-12-28 15:45 UTC, BohdanGres commented on app.js
>  app.use('/api/contacts', contactsRouter);
спробуй зробити так що б запрацювало

2022-12-28 15:46 UTC, BohdanGres approved these changes

2022-12-28 18:50 UTC, merged